# Generated by Django 4.1.6 on 2023-04-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_comments_alter_comment_id_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
